  [[main]]
  name = "Trang chủ"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Bài Viết"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Danh mục dự án"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Chứng chỉ"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
 

  [[footer]]
  name = "about"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"